layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: '' # an empty string here means all files in the project
      type: 'posts'
    values:
      layout: 'post'

projects:
  sort_by: stars
  limit: 12
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  linkedin: rodrigobdz

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning

  - name: Deep Learning
    web_url: https://github.com/topics/deep-learning

  - name: Code Quality
    web_url: https://github.com/topics/code-quality

  - name: Shell
    web_url: https://github.com/topics/shell

  - name: Bash
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/bash/bash.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Raspberry Pi
    web_url: https://github.com/topics/raspberry-pi
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/raspberry-pi/raspberry-pi.png
