#!/usr/bin/env bash
#
# Start a local server.

set -o errexit
set -o pipefail
set -o nounset

# shellcheck disable=SC1091
source utils.sh

fancy_echo "Open http://localhost:1313/ in the default browser"
open http://localhost:1313/

fancy_echo "Start a local server"
hugo server
